# -*- coding: utf-8 -*-
"""basic.program

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1D984PwPuxlXAg7ApZ3sKIEhWGwcVQXnI
"""

# Basic Calculator Program
def add(a, b):
    return a + b

def subtract(a, b):
    return a - b

def multiply(a, b):
    return a * b

def divide(a, b):
    if b != 0:
        return a / b
    else:
        return "Error! Division by zero."

# Main Program
if __name__ == "__main__":
    print("Welcome to the Basic Calculator!")
    print("Enter two numbers:")
    num1 = float(input("First number: "))
    num2 = float(input("Second number: "))

    print("\nSelect an operation:")
    print("1. Add")
    print("2. Subtract")
    print("3. Multiply")
    print("4. Divide")
    choice = input("Enter choice (1/2/3/4): ")

    if choice == "1":
        print(f"The result of addition: {add(num1, num2)}")
    elif choice == "2":
        print(f"The result of subtraction: {subtract(num1, num2)}")
    elif choice == "3":
        print(f"The result of multiplication: {multiply(num1, num2)}")
    elif choice == "4":
        print(f"The result of division: {divide(num1, num2)}")
    else:
        print("Invalid choice!")